FROM ghcr.io/structmap/cljr-net9.0
USER 0
RUN apt update -y
RUN apt install -y sudo procps
ARG USERNAME=app
RUN echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME
USER app
